sonar.projectKey=logos-co_logos-scaffold
sonar.organization=logos-co

sonar.sources=src
sonar.tests=tests
sonar.language=rust

sonar.rust.cargo.manifestPath=Cargo.toml

sonar.coverage.exclusions=**/tests/**,**/test_*/**
sonar.exclusions=**/target/**,**/.git/**,**/node_modules/**