use std::fs;
use std::path::Path;

use crate::state::write_text;
use crate::template::runners::{
    render_runner_run_hello_world, render_runner_run_hello_world_private,
    render_runner_run_hello_world_through_tail_call,
    render_runner_run_hello_world_through_tail_call_private,
    render_runner_run_hello_world_with_authorization,
    render_runner_run_hello_world_with_authorization_through_tail_call_with_pda,
    render_runner_run_hello_world_with_move_function, render_runner_support_lib,
};
use crate::DynResult;

pub(crate) fn render_project_template_cargo(crate_name: &str, lssa_pin: &str) -> String {
    format!(
        "[package]\nname = \"{crate_name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\nlicense = {{ workspace = true }}\n\n[workspace.package]\nlicense = \"MIT or Apache-2.0\"\n\n[workspace]\nresolver = \"3\"\nmembers = [\n  \".\",\n  \"methods\",\n  \"methods/guest\",\n]\n\n[workspace.dependencies]\nnssa = {{ git = \"https://github.com/logos-blockchain/lssa.git\", rev = \"{lssa_pin}\" }}\nnssa_core = {{ git = \"https://github.com/logos-blockchain/lssa.git\", rev = \"{lssa_pin}\" }}\nwallet = {{ git = \"https://github.com/logos-blockchain/lssa.git\", rev = \"{lssa_pin}\" }}\n\nrisc0-zkvm = {{ version = \"3.0.5\", features = [\"std\"] }}\nrisc0-build = \"3.0.5\"\n\nhex = \"0.4.3\"\nbytemuck = \"1.24.0\"\ntokio = {{ version = \"1.28.2\", features = [\"macros\", \"net\", \"rt-multi-thread\", \"sync\", \"fs\"] }}\nclap = {{ version = \"4.5.42\", features = [\"derive\", \"env\"] }}\n\n[dependencies]\nnssa.workspace = true\nnssa_core.workspace = true\nwallet.workspace = true\nexample_program_deployment_methods = {{ path = \"methods\" }}\n\nclap.workspace = true\ntokio = {{ workspace = true, features = [\"macros\"] }}\n"
    )
}

pub(crate) fn render_scaffolded_project_readme() -> String {
    r#"# Program Deployment Scaffold

This project was generated by `logos-scaffold` for LSSA standalone mode only.

## Prerequisites

- `git`, `rustc`, `cargo`
- `wallet` binary (installed by `logos-scaffold setup`)
- Docker running (required by guest method builds)

## First Run

```bash
logos-scaffold setup
logos-scaffold localnet start
export NSSA_WALLET_HOME_DIR=$(pwd)/.scaffold/wallet
logos-scaffold build
export EXAMPLE_PROGRAMS_BUILD_DIR=$(pwd)/target/riscv-guest/example_program_deployment_methods/example_program_deployment_programs/riscv32im-risc0-zkvm-elf/release
wallet check-health
```

## Deploy Guest Programs

```bash
wallet deploy-program "$EXAMPLE_PROGRAMS_BUILD_DIR/hello_world.bin"
wallet deploy-program "$EXAMPLE_PROGRAMS_BUILD_DIR/hello_world_with_authorization.bin"
wallet deploy-program "$EXAMPLE_PROGRAMS_BUILD_DIR/hello_world_with_move_function.bin"
wallet deploy-program "$EXAMPLE_PROGRAMS_BUILD_DIR/simple_tail_call.bin"
wallet deploy-program "$EXAMPLE_PROGRAMS_BUILD_DIR/tail_call_with_pda.bin"
```

## Create Accounts

Create fresh accounts and assign their IDs to shell vars:

```bash
# copy IDs from wallet output
PUBLIC_HELLO_ACCOUNT_ID="<public-account-id>"
PRIVATE_HELLO_ACCOUNT_ID="<private-account-id>"
PUBLIC_AUTH_ACCOUNT_ID="<public-account-id>"
PUBLIC_MOVE_ACCOUNT_ID="<public-account-id>"
PRIVATE_MOVE_ACCOUNT_ID="<private-account-id>"
```

Use `wallet account new public` and `wallet account new private` enough times to fill those values.

## Run All Example Binaries

```bash
cargo run --bin run_hello_world -- $PUBLIC_HELLO_ACCOUNT_ID

cargo run --bin run_hello_world_private -- $PRIVATE_HELLO_ACCOUNT_ID
wallet account sync-private

cargo run --bin run_hello_world_with_authorization -- $PUBLIC_AUTH_ACCOUNT_ID

cargo run --bin run_hello_world_with_move_function -- \
  write-public \
  $PUBLIC_MOVE_ACCOUNT_ID \
  "hello-from-public"

cargo run --bin run_hello_world_with_move_function -- \
  write-private \
  $PRIVATE_MOVE_ACCOUNT_ID \
  "hello-from-private"
wallet account sync-private

cargo run --bin run_hello_world_with_move_function -- \
  move-data-public-to-private \
  $PUBLIC_MOVE_ACCOUNT_ID \
  $PRIVATE_MOVE_ACCOUNT_ID
wallet account sync-private

cargo run --bin run_hello_world_through_tail_call -- $PUBLIC_HELLO_ACCOUNT_ID

cargo run --bin run_hello_world_through_tail_call_private -- $PRIVATE_MOVE_ACCOUNT_ID
wallet account sync-private

cargo run --bin run_hello_world_with_authorization_through_tail_call_with_pda
```

## Optional Program Path Overrides

For testing custom binaries, pass explicit paths:

```bash
cargo run --bin run_hello_world -- --program-path "$EXAMPLE_PROGRAMS_BUILD_DIR/hello_world.bin" $PUBLIC_HELLO_ACCOUNT_ID
cargo run --bin run_hello_world_through_tail_call_private -- --simple-tail-call-path "$EXAMPLE_PROGRAMS_BUILD_DIR/simple_tail_call.bin" --hello-world-path "$EXAMPLE_PROGRAMS_BUILD_DIR/hello_world.bin" $PRIVATE_MOVE_ACCOUNT_ID
```

## Main Scaffold Commands

```bash
logos-scaffold setup
logos-scaffold build [project-path]
logos-scaffold localnet start
logos-scaffold localnet status
logos-scaffold localnet logs --tail 200
logos-scaffold localnet stop
logos-scaffold doctor
```

## Notes

- Standalone-only: no `logos-blockchain` dependency and no `deps` or `example` CLI groups.
- Use `export NSSA_WALLET_HOME_DIR=$(pwd)/.scaffold/wallet` before wallet commands.
- `logos-scaffold build` runs `setup` and then `cargo build --workspace`.
- LSSA pin is enforced by `logos-scaffold setup`.
- `simple_tail_call` hardcodes `HELLO_WORLD_PROGRAM_ID_HEX`. If tail-call runs fail, set it to the `hello_world.bin` ImageID from the latest `cargo risczero build` output, then rebuild methods.
"#
    .to_string()
}

pub(crate) fn apply_scaffold_dx_overrides(target: &Path) -> DynResult<()> {
    fs::create_dir_all(target.join("src/bin"))?;

    write_text(
        &target.join(".gitignore"),
        ".scaffold/\ntarget/\nCargo.lock.bak\n",
    )?;

    write_text(&target.join("src/lib.rs"), &render_runner_support_lib())?;
    write_text(
        &target.join("src/bin/run_hello_world.rs"),
        &render_runner_run_hello_world(),
    )?;
    write_text(
        &target.join("src/bin/run_hello_world_private.rs"),
        &render_runner_run_hello_world_private(),
    )?;
    write_text(
        &target.join("src/bin/run_hello_world_with_authorization.rs"),
        &render_runner_run_hello_world_with_authorization(),
    )?;
    write_text(
        &target.join("src/bin/run_hello_world_through_tail_call.rs"),
        &render_runner_run_hello_world_through_tail_call(),
    )?;
    write_text(
        &target.join("src/bin/run_hello_world_through_tail_call_private.rs"),
        &render_runner_run_hello_world_through_tail_call_private(),
    )?;
    write_text(
        &target.join("src/bin/run_hello_world_with_authorization_through_tail_call_with_pda.rs"),
        &render_runner_run_hello_world_with_authorization_through_tail_call_with_pda(),
    )?;
    write_text(
        &target.join("src/bin/run_hello_world_with_move_function.rs"),
        &render_runner_run_hello_world_with_move_function(),
    )?;

    Ok(())
}
